package biologics.pp.adapter.registration.material;

import genedata.bx.adapter.register.material.MaterialPreRegistrationAdapter;
import genedata.bx.adapter.register.material.MaterialPreRegistrationCallback;
import genedata.bx.adapter.register.material.MaterialPreRegistrationOptions;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;

/**
 * Example implementation of the material pre-registration adapter.
 * External material identifiers are generated by concatenating
 * a timestamp to the given qualified identifiier of the Biologics
 * material entity.
 * 
 * <div style="font-size:x-small">
 * Copyright 2014 Genedata AG. All Rights Reserved.
 * </div>
 */
public class ExampleMaterialPreRegistration implements MaterialPreRegistrationAdapter, Serializable {
	private static final long serialVersionUID = 1L;
	
	@Override
	public void setConfiguration(Map<String, String> configuration) {
		// nothing to do here
	}
	
	@Override
	public void options(MaterialPreRegistrationOptions options) {
		// nothing to do here
	}
	
	@Override
	public void perform(MaterialPreRegistrationCallback biologics) {
		String materialQualifiedId = biologics.getMaterialQualifiedId();
		
		String externalMaterialIdentifier = generateExternalMaterialIdentifier(materialQualifiedId);
		
		biologics.setExternalMaterialIdentifier(externalMaterialIdentifier);
		
		biologics.getReporter().info(
			"Successfully pre-registered the material #0 (example implementation).",
			materialQualifiedId);
	}
	
	/**
	 * In this example implementation, the external material identifier is
	 * generated by simply adding a timestamp to the qualified identifier
	 * of the Biologics material.
	 * @param materialQualifiedId The qualified identifier of the Biologics material.
	 * @return The generated external material identifier.
	 */
	private String generateExternalMaterialIdentifier(String materialQualifiedId) {
		String timeStamp = new Date().toString();
		return materialQualifiedId + " [" + timeStamp + "]";
	}
	
}
