lib.dir=lib
src.dir=src/main
src.gen.dir=src/generated
stage.dir=staging
classes.dir=${stage.dir}/classes
jar.name=customer-ws-client-implementations.jar
result.dir=dist
deploy.project.dir=../../Lib/gdb-adapters
